### ISSUE TITLE
Conduct some playtests

### ISSUE THREAD

**Issue by RemiEven** [AcevedoR/outplant#21]
-> Ensure most games last for about 3 min

**Comment by AcevedoR** [comment]
feedback from a gamedev/friend (FR):

- Il faut + de feedback systematique sur les clicks (audio, visuel)
- Et feedback de l'impact de ce que tu fais
- Et pas des gros pavé de texte, ou alors avec un meilleur formatage

**Comment by AcevedoR** [comment]
#66 #87 were created to try to address these feedbacks
